swagger: "2.0"
info:
  description: "Trusty XAI service description."
  version: "1.0.0"
  title: "TrustyXAI"
  termsOfService: "http://kie.org/trusty/"
  contact:
    email: "tteofili@redhat.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "kie.org"
basePath: "/xai"
tags:
  - name: "local"
    description: "Local explanations"
    externalDocs:
      description: "Find out more"
      url: "http://kie.org"
  - name: "global"
    description: "Global explanations"
    externalDocs:
      description: "Find out more"
      url: "http://kie.org"
schemes:
  - "https"
  - "http"
paths:
  /local/saliency/lime:
    post:
      tags:
        - "local"
      summary: "Execute LIME explanation method on a prediction"
      description: ""
      operationId: "lime"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Prediction that needs to be explained"
          required: true
          schema:
            $ref: "https://raw.githubusercontent.com/kiegroup/trusty-ai-sandbox/master/explainability/service/xai-poc-v2/xai-api/src/main/resources/xai.yaml#/definitions/Prediction"
      responses:
        200:
          description: "successful explanation"
          schema:
            $ref: "https://raw.githubusercontent.com/kiegroup/trusty-ai-sandbox/master/explainability/service/xai-poc-v2/xai-api/src/main/resources/xai.yaml#/definitions/Saliency"
      security:
        - trusty_auth:
            - "write:exp"
            - "read:exp"
  /global/tabular/pdp:
    post:
      tags:
        - "global"
      summary: "PDP explanation method on a model"
      description: ""
      operationId: "pdp"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Model that needs to be explained"
          required: true
          schema:
            $ref: "https://raw.githubusercontent.com/kiegroup/trusty-ai-sandbox/master/explainability/service/xai-poc-v2/m2x-api/src/main/resources/m2x.yaml#/definitions/ModelInfo"
      responses:
        200:
          description: "pdp graphs, one for each pair <feature, output>"
          schema:
            type: "array"
            items:
              $ref: "https://raw.githubusercontent.com/kiegroup/trusty-ai-sandbox/master/explainability/service/xai-poc-v2/xai-api/src/main/resources/xai.yaml#/definitions/TabularData"
      security:
        - trusty_auth:
            - "write:exp"
            - "read:exp"
securityDefinitions:
  trusty_auth:
    type: "oauth2"
    authorizationUrl: "http://kie.org/oauth/dialog"
    flow: "implicit"
    scopes:
      write:exp: "execute explanations"
      read:exp: "read explanations"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"