name: Trusty CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Install kogito-runtimes trusty patch
      run: cd end2endPoC && ./setup.sh && cd ..
    - name: Build services and run docker compose
      run: cd end2endPoC && ./run-compose.sh -d && cd ..
    - name: wait until mongodb is responsive
      run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:27017)" != "200" ]]; do sleep 5; done' || false
    - name: add test user to mongodb
      run: mongo admin -u root -p password --host localhost:27017 < ./end2endPoC/pipelines/add-mongo-user.js
    - name: Run integration tests
      run: mvn -f end2endPoC-integrationTests/pom.xml test
